# Generated by Django 5.1.3 on 2024-11-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('pkBrokerID', models.IntegerField(primary_key=True, serialize=False)),
                ('fldBrokerName', models.CharField(max_length=255)),
                ('fldForeignCompany', models.CharField(blank=True, max_length=255, null=True)),
                ('SortOrdertblBroker', models.CharField(blank=True, max_length=10, null=True)),
                ('fldfarsiBrokerName', models.CharField(blank=True, max_length=255, null=True)),
                ('fldBrokerMaxDebtInUSD', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('SCode', models.IntegerField()),
            ],
            options={
                'db_table': 'tblBroker',
            },
        ),
        migrations.CreateModel(
            name='CashIn',
            fields=[
                ('pkCashIn', models.AutoField(primary_key=True, serialize=False)),
                ('fkClientID', models.IntegerField()),
                ('fkBrokerID', models.IntegerField()),
                ('fkForeignCurrencyID', models.IntegerField()),
                ('fldCashInDate', models.DateTimeField()),
                ('fldCashInAmount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('fldRefrence', models.CharField(blank=True, max_length=255, null=True)),
                ('fldCompanyWageCoeff', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('fldBrokerWageCoeff', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('fldNetCashIn', models.DecimalField(decimal_places=4, max_digits=18)),
                ('fldCompanyWage', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('fldBrokerWage', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('fkDestinationCurrency', models.IntegerField()),
                ('fldXERate', models.DecimalField(decimal_places=4, max_digits=18)),
                ('fldCashInNet_Dest_currency', models.DecimalField(decimal_places=4, max_digits=18)),
                ('fldRegisterDate', models.DateTimeField()),
                ('fldReverseExchange', models.IntegerField(default=0)),
                ('PassedDate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cash In',
                'verbose_name_plural': 'Cash Ins',
                'db_table': 'tblCashIn',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('pkClientID', models.AutoField(primary_key=True, serialize=False)),
                ('fldClientName', models.CharField(max_length=255)),
                ('SortOrderClient', models.CharField(blank=True, max_length=10, null=True)),
                ('SCode', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'tblClient',
            },
        ),
        migrations.CreateModel(
            name='ForeignCurrency',
            fields=[
                ('pkForeignCurrencyID', models.AutoField(primary_key=True, serialize=False)),
                ('fldForeignCurrencyName', models.CharField(max_length=50)),
                ('fldForeignCurrency2USD', models.DecimalField(decimal_places=4, max_digits=10)),
                ('SCode', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Foreign Currency',
                'verbose_name_plural': 'Foreign Currencies',
                'db_table': 'tblForeignCurrency',
            },
        ),
    ]
